# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/android:api-26-alpha
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
    
      - checkout
        
      - run: chmod +x ~/repo/.circleci/sumsrc.sh
        
      - run: ~/repo/.circleci/sumsrc.sh
    
      # Download and cache dependencies
      - restore_cache:
          keys:
            - jars-{{ checksum "build.gradle" }}-{{ checksum "mobile/build.gradle" }}

      - run: ./gradlew androidDependencies
          
      # run tests!
      - run: ./gradlew :mobile:checkstyle
      - run: ./gradlew :mobile:pmd
      - run: ./gradlew :mobile:findbugs
      - run: ./gradlew assembleDebug
      
      - save_cache:
          paths:
            - ~/.m2
            - ~/.gradle
          key: jars-{{ checksum "build.gradle"}}-{{ checksum "mobile/build.gradle" }}
      
      - store_artifacts:
          path: mobile/build/outputs
          destination: apks
          
      - store_artifacts:
          path: mobile/build/reports
          destination: reports
